// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: printer.proto

package printer;

public interface PowerResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:printer.PowerResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool switch = 1;</code>
   */
  boolean getSwitch();
}
