// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: printer.proto

package printer;

public interface PrinterResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:printer.PrinterResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 printer = 1;</code>
   */
  int getPrinter();
}
