// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: printproduct.proto

package printProduct;

public interface PowerResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:printProduct.PowerResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool switch = 1;</code>
   */
  boolean getSwitch();
}
