// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: printproduct.proto

package printProduct;

public interface PrinterRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:printProduct.PrinterRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 printer = 1;</code>
   */
  int getPrinter();
}
