// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: printproduct.proto

package printProduct;

public final class PrintProductServiceImpl {
  private PrintProductServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_printProduct_PowerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_printProduct_PowerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_printProduct_PowerResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_printProduct_PowerResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_printProduct_PrinterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_printProduct_PrinterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_printProduct_PrinterResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_printProduct_PrinterResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022printproduct.proto\022\014printProduct\"\036\n\014Po" +
      "werRequest\022\016\n\006switch\030\001 \001(\010\"\037\n\rPowerRespo" +
      "nse\022\016\n\006switch\030\001 \001(\010\"!\n\016PrinterRequest\022\017\n" +
      "\007printer\030\001 \001(\005\"\"\n\017PrinterResponse\022\017\n\007pri" +
      "nter\030\001 \001(\0052\261\001\n\023PrintProductService\022H\n\013sw" +
      "itchPower\022\032.printProduct.PowerRequest\032\033." +
      "printProduct.PowerResponse\"\000\022P\n\rprintPro" +
      "ducts\022\034.printProduct.PrinterRequest\032\035.pr" +
      "intProduct.PrinterResponse\"\0000\001B)\n\014printP" +
      "roductB\027PrintProductServiceImplP\001b\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_printProduct_PowerRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_printProduct_PowerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_printProduct_PowerRequest_descriptor,
        new java.lang.String[] { "Switch", });
    internal_static_printProduct_PowerResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_printProduct_PowerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_printProduct_PowerResponse_descriptor,
        new java.lang.String[] { "Switch", });
    internal_static_printProduct_PrinterRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_printProduct_PrinterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_printProduct_PrinterRequest_descriptor,
        new java.lang.String[] { "Printer", });
    internal_static_printProduct_PrinterResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_printProduct_PrinterResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_printProduct_PrinterResponse_descriptor,
        new java.lang.String[] { "Printer", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
