package WelcomeMsg;


/**
* WelcomeMsg/_WelcomemsgImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WelcomeMsg.idl
* Friday 21 August 2020 at 00:01:34 British Summer Time
*/

public abstract class _WelcomemsgImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements WelcomeMsg.Welcomemsg, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _WelcomemsgImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("welcomeMsg", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // WelcomeMsg/Welcomemsg/welcomeMsg
       {
         String $result = null;
         $result = this.welcomeMsg ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:WelcomeMsg/Welcomemsg:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _WelcomemsgImplBase
