package WelcomeMsg;


/**
* WelcomeMsg/WelcomemsgOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WelcomeMsg.idl
* Friday 21 August 2020 at 00:01:34 British Summer Time
*/

public interface WelcomemsgOperations 
{
  String welcomeMsg ();
} // interface WelcomemsgOperations
