package WelcomeMsg;

/**
* WelcomeMsg/WelcomemsgHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WelcomeMsg.idl
* Friday 21 August 2020 at 00:01:34 British Summer Time
*/

public final class WelcomemsgHolder implements org.omg.CORBA.portable.Streamable
{
  public WelcomeMsg.Welcomemsg value = null;

  public WelcomemsgHolder ()
  {
  }

  public WelcomemsgHolder (WelcomeMsg.Welcomemsg initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = WelcomeMsg.WelcomemsgHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    WelcomeMsg.WelcomemsgHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return WelcomeMsg.WelcomemsgHelper.type ();
  }

}
