// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

package product;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:product.Empty)
    com.google.protobuf.MessageOrBuilder {
}
