// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

package product;

public interface productsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:product.productsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string products = 1;</code>
   */
  java.lang.String getProducts();
  /**
   * <code>string products = 1;</code>
   */
  com.google.protobuf.ByteString
      getProductsBytes();
}
