// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

package product;

public final class ProductServiceImpl {
  private ProductServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_product_productsItem_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_product_productsItem_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_product_productsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_product_productsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_product_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_product_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rproduct.proto\022\007product\" \n\014productsItem" +
      "\022\020\n\010products\030\001 \001(\t\"$\n\020productsResponse\022\020" +
      "\n\010products\030\001 \001(\t\"\007\n\005Empty2X\n\016ProductServ" +
      "ice\022F\n\014productItems\022\025.product.productsIt" +
      "em\032\031.product.productsResponse\"\000(\0010\001B\037\n\007p" +
      "roductB\022ProductServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_product_productsItem_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_product_productsItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_product_productsItem_descriptor,
        new java.lang.String[] { "Products", });
    internal_static_product_productsResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_product_productsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_product_productsResponse_descriptor,
        new java.lang.String[] { "Products", });
    internal_static_product_Empty_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_product_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_product_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
